module: "module-1"
id: "pipeline-1"
topics:
  - name: "questions-topic"
    creation-mode: create-if-not-exists
  - name: "answers-topic"
    creation-mode: create-if-not-exists
pipeline:
  - name: "convert-to-structure"
    id: "convert-to-structure"
    type: "document-to-json"
    input: "questions-topic"
    configuration:
      field: "question"
  - name: "compute-embeddings"
    id: "compute-embeddings"
    type: "compute-ai-embeddings"
    input: "questions-topic"
    configuration:
      model: "text-embedding-ada-002" # This needs to match the name of the model deployment, not the base model
      embeddings-field: "value.question_embeddings"
      text: "{{% value.question }}"
  - name: "lookup-related-documents-in-llm"
    type: "query"
    configuration:
      datasource: "AstraDatasource"
      query: "SELECT text FROM documents ORDER BY item_vector ANN OF ? LIMIT 5"
      fields:
        - "value.question_embeddings"
      output-field: "value.related_documents"
  - name: "ai-chat-completions"
    type: "ai-chat-completions"
    output: "answers-topic"
    configuration:
      model: "gpt-35-turbo" # This needs to be set to the model deployment name, not the base name
      completion-field: "value.answer"
      log-field: "value-prompt"
      messages:
        - role: system
          content: |
              An user is going to perform a questions, these documents may help you in answering to their questions.
              {{%# value.related_documents}}
              {{% text}}
              {{%/ value.related_documents}}
        - role: user
          content: "{{% value}}"
