{{- if .Values.deployer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "langstream.deployerServiceAccountName" . }}
  labels:
    {{- include "langstream.deployerLabels" . | nindent 4 }}
  {{- with .Values.deployer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "langstream.deployerRoleName" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "langstream.deployerRoleBindingName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "langstream.deployerRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "langstream.deployerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "langstream.deployerRoleName" . }}
rules:
  - apiGroups:
    - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - langstream.ai
    resources:
      - agents
      - agents/status
      - applications
      - applications/status
    verbs:
      - "*"
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - "*"
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "langstream.deployerRoleBindingName" . }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "langstream.deployerRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "langstream.deployerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- end }}

