apiVersion: v1
kind: Namespace
metadata:
  name: herddb-dev
  labels:
    name: herddb-dev
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: herddb
  name: herddb
  namespace: herddb-dev
spec:
  containers:
  - name: herddb
    image: herddb/herddb:0.28.0
    ports:
      -  containerPort: 7000
         protocol: TCP
         name: herddb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: herddb
  name: herddb
  namespace: herddb-dev # Change this value to match the namespace metadata.name
spec:
  ports:
    - port: 7000
      protocol: TCP
      targetPort: 7000
      name: herddb
  selector:
    app: herddb