
controlPlane:
  image:
    pullPolicy: Never
    tag: "latest-dev"
  app:
    config:
      logging.level.com.datastax.oss.sga: debug
      application.storage.apps.type: kubernetes
      application.storage.apps.configuration.namespaceprefix: sga-
      application.storage.apps.configuration.deployer-runtime.image: datastax/sga-runtime:latest-dev
      application.storage.apps.configuration.deployer-runtime.image-pull-policy: Never
      application.storage.global.type: kubernetes
      application.storage.code.type: s3
      application.storage.code.configuration.endpoint: http://minio.minio-dev.svc.cluster.local:9000
      application.storage.code.configuration.access-key: minioadmin
      application.storage.code.configuration.secret-key: minioadmin

deployer:
  replicaCount: 1
  image:
    repository: datastax/sga-deployer
    pullPolicy: Never
    tag: "latest-dev"
  app:
    config:
      codeStorage:
        type: s3
        endpoint: http://minio.minio-dev.svc.cluster.local:9000
        access-key: minioadmin
        secret-key: minioadmin