controlPlane:
  image:
    pullPolicy: Never
    tag: "latest-dev"
  app:
    config:
      logging.level.com.datastax.oss.sga: debug
      application.storage.global.type: kubernetes

deployer:
  replicaCount: 1
  image:
    repository: datastax/sga-deployer
    pullPolicy: Never
    tag: "latest-dev"
  app:
    config: {}


client:
  replicaCount: 1
  image:
    repository: datastax/sga-cli
    pullPolicy: Never
    tag: "latest-dev"

apiGateway:
  image:
    pullPolicy: Never
    tag: "latest-dev"
  app:
    config:
      logging.level.com.datastax.oss.sga: debug


codeStorage:
  type: s3
  configuration:
    endpoint: http://minio.minio-dev.svc.cluster.local:9000
    access-key: minioadmin
    secret-key: minioadmin