controlPlane:
  image:
    pullPolicy: Never
    repository: langstream/langstream-control-plane
    tag: "latest-dev"
  app:
    config:
      logging.level.ai.langstream: debug
      application.storage.global.type: kubernetes

deployer:
  replicaCount: 1
  image:
    repository: langstream/langstream-deployer
    pullPolicy: Never
    tag: "latest-dev"
  app:
    config: {}

runtime:
  image: langstream/langstream-runtime:latest-dev
  imagePullPolicy: Never

client:
  replicaCount: 1
  image:
    repository: langstream/langstream-cli
    pullPolicy: Never
    tag: "latest-dev"

apiGateway:
  image:
    repository: langstream/langstream-api-gateway
    pullPolicy: Never
    tag: "latest-dev"
  app:
    config:
      logging.level.ai.langstream: debug


codeStorage:
  type: s3
  configuration:
    endpoint: http://minio.minio-dev.svc.cluster.local:9000
    access-key: minioadmin
    secret-key: minioadmin
