
controlPlane:
  image:
    pullPolicy: Never
    tag: "latest-dev"
  app:
    config:
      application.storage.apps.type: kubernetes
      application.storage.apps.configuration.namespaceprefix: sga-
      application.storage.apps.configuration.deployer-runtime.image: datastax/sga-runtime:latest-dev
      application.storage.apps.configuration.deployer-runtime.image-pull-policy: Never
      application.storage.global.type: kubernetes

deployer:
  replicaCount: 1
  image:
    repository: datastax/sga-deployer
    pullPolicy: Never
    tag: "latest-dev"
