# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

controlPlane:
  image:
    pullPolicy: Always
    tag: latest
    repository: us-central1-docker.pkg.dev/datastax-gcp-pulsar/pulsar/sga-control-plane
  app:
    config:
      application.storage.apps.type: kubernetes
      application.storage.apps.configuration.namespaceprefix: sga-
      application.storage.apps.configuration.deployer-runtime.image: us-central1-docker.pkg.dev/datastax-gcp-pulsar/pulsar/sga-runtime
      application.storage.apps.configuration.deployer-runtime.image-pull-policy: Always
      application.storage.global.type: kubernetes
      application.storage.code.type: s3
      application.storage.code.configuration.endpoint: http://minio.minio-dev.svc.cluster.local:9000

deployer:
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/datastax-gcp-pulsar/pulsar/sga-deployer
    pullPolicy: Always
    tag: latest
  app:
    config:
      codeStorage:
        type: s3
        endpoint: http://minio.minio-dev.svc.cluster.local:9000
