
controlPlane:
  replicaCount: 1
  image:
    repository: datastax/sga-control-plane
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    role:
      name: "sga-control-plane"
    roleBinding:
      name: "sga-control-plane-role-binding"

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 8090
  resources:
    requests:
       cpu: 200m
       memory: 256Mi
  liveness:
    initialDelaySeconds: 20
    timeoutSeconds: 5
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
  nodeSelector: {}
  tolerations: []
  affinity: {}
  app:
    config:

      application.storage.apps.type: kubernetes
      application.storage.apps.configuration.namespaceprefix: sga-
      application.storage.apps.configuration.deployer-runtime.image: datastax/sga-runtime:latest-dev
      application.storage.apps.configuration.deployer-runtime.image-pull-policy: Never
      application.storage.global.type: kubernetes

deployer:
  replicaCount: 1
  image:
    repository: datastax/sga-deployer
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
    role:
      name: "sga-deployer"
    roleBinding:
      name: "sga-deployer-role-binding"
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  app:
    config:
      agentResources: {}
      clusterRuntime:
        kubernetes:
          namespace-prefix: sga-
          image: datastax/sga-runtime:latest-dev
          image-pull-policy: Never
      codeStorage:
        type: none
        endpoint: ""
