{{- if .Values.controlPlane.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "langstream.controlPlaneServiceAccountName" . }}
  labels:
    {{- include "langstream.controlPlaneLabels" . | nindent 4 }}
  {{- with .Values.controlPlane.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "langstream.controlPlaneRoleName" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "langstream.controlPlaneRoleBindingName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "langstream.controlPlaneRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "langstream.controlPlaneServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "langstream.controlPlaneRoleName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - secrets
      - serviceaccounts
      - pods
      - pods/log
    verbs:
      - "*"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
      - rolebindings
    verbs:
      - "*"
  - apiGroups:
      - langstream.ai
    resources:
      - agents
      - agents/status
      - applications
      - applications/status
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "langstream.controlPlaneRoleBindingName" . }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "langstream.controlPlaneRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "langstream.controlPlaneServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
