{{- if .Values.apiGateway.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "langstream.apiGatewayServiceAccountName" . }}
  labels:
    {{- include "langstream.apiGatewayLabels" . | nindent 4 }}
  {{- with .Values.apiGateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "langstream.apiGatewayRoleName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/status
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - langstream.ai
    resources:
      - applications
      - applications/status
      - agents
      - agents/status
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "langstream.apiGatewayRoleBindingName" . }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "langstream.apiGatewayRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "langstream.apiGatewayServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
