apiVersion: v1
kind: Service
metadata:
  name: {{ include "langstream.apiGatewayFullname" . }}
  labels:
    {{- include "langstream.apiGatewayLabels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "langstream.apiGatewaySelectorLabels" . | nindent 4 }}
