module: "module-1"
id: "pipeline-1"
name: "Read from S3"
topics:
  - name: "output-topic"
    creation-mode: create-if-not-exists
pipeline:
  - name: "Read from S3"
    type: "s3-source"
    output: "output-topic"
    configuration:
      bucketName: sga-source
      endpoint: "https://s3.eu-west-2.amazonaws.com"
      username: "{{ secrets.s3.username }}"
      password: "{{ secrets.s3.password }}"
      idle-time: 5