apiVersion: v1
kind: Service
metadata:
  name: {{ include "sga.controlPlaneFullname" . }}
  labels:
    {{- include "sga.controlPlaneLabels" . | nindent 4 }}
spec:
  type: {{ .Values.controlPlane.service.type }}
  ports:
    - port: {{ .Values.controlPlane.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sga.controlPlaneSelectorLabels" . | nindent 4 }}
