module: "module-1"
id: "pipeline-1"
topics:
  - name: "input-topic"
    creation-mode: create-if-not-exists
  - name: "output-topic"
    creation-mode: create-if-not-exists
pipeline:
  - name: "chat-ai-completions"
    type: "chat-ai-completions"
    input: "input-topic"
    output: "output-topic"
    configuration:
      model: "gpt-3.5-turbo"
      output-field: "value"
      messages:
        role: user
        message: "What can you tell me about {{% value}} ?"