configuration:
  resources:
    - type: "vertex-configuration"
      name: "Google Vertex AI configuration"
      configuration:
        url: "{{ secrets.vertex-ai.url }}"
        token: "{{ secrets.vertex-ai.token }}"
        region: "{{ secrets.vertex-ai.region }}"
        project: "{{ secrets.vertex-ai.project }}"
