# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: Unit tests (${{ matrix.name }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Runtime
          - name: Deployer
          - name: Api Gateway
          - name: Control plane
          - name: Other
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: Java 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: 'Setup: Python 3.11'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Init: build project'
        run: |
          chmod +x mvnw
          ./mvnw clean install -DskipTests

      - name: 'Init: install tox'
        if: ${{ matrix.name == 'Runtime' }}
        run: pip install -r requirements.txt

      - name: 'Test: Runtime'
        if: ${{ matrix.name == 'Runtime' }}
        run: |
          ./mvnw verify -pl ":sga-runtime-impl" -Pdocker

      - name: 'Test: Api Gateway'
        if: ${{ matrix.name == 'Api Gateway' }}
        run: |
          ./mvnw verify -pl ":api-gateway" -Pdocker

      - name: 'Test: Deployer'
        if: ${{ matrix.name == 'Deployer' }}
        run: |
          ./mvnw verify -f k8s-deployer -Pdocker

      - name: 'Test: Control plane'
        if: ${{ matrix.name == 'Control plane' }}
        run: |
          ./mvnw verify -pl webservice -Pdocker

      - name: 'Test: Other'
        if: ${{ matrix.name == 'Other' }}
        run: |
          #/bin/bash
          ./mvnw verify -PtestSuiteOthers
  e2e-tests:
    name: End to End tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: Java 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - uses: azure/setup-helm@v3
        with:
          version: v3.7.0

      - uses: azure/setup-kubectl@v3
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1


      - name: 'Build and test'
        run: |
          chmod +x mvnw
          uname -m
          eval $(minikube docker-env)
          ./docker/build.sh
          docker pull quay.io/strimzi/kafka:0.36.0-kafka-3.5.0
          eval $(minikube docker-env -u)
          ./mvnw install -pl e2e-tests -am -DskipTests
          ./mvnw verify -pl e2e-tests -De2eTests  

      - name: Upload Surefire reports
        uses: actions/upload-artifact@v3
        if: failure()
        continue-on-error: true
        with:
          name: test-logs-${{ matrix.group }}
          path: "**/target/e2e-test-logs/*"
          retention-days: 7
