name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  #--------------------------------------------------
  # Build and Tests the project on Linux
  #--------------------------------------------------
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Runtime
          - name: Other
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: Java 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: 'Setup: Python 3.11'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Test: run tests'
        run: |
          chmod +x mvnw
          ./mvnw clean install -Pdocker -DskipTests

      - name: 'Init: install tox'
        if: ${{ matrix.name == 'Runtime' }}
        run: pip install -r requirements.txt

      - name: 'Test: run tests'
        if: ${{ matrix.name == 'Runtime' }}
        run: |
          ./mvnw verify -pl ":sga-runtime-impl"

      - name: 'Test: run tests'
        if: ${{ matrix.name == 'Other' }}
        run: |
          ./mvnw verify -pl "!:sga-runtime-impl"
  e2e-tests:
    name: e2e-tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: Java 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17.x'
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - uses: azure/setup-helm@v3
        with:
          version: v3.7.0

      - uses: azure/setup-kubectl@v3

      - name: 'Build and test'
        run: |
          chmod +x mvnw
          uname -m
          eval $(minikube docker-env)
          ./docker/build.sh
          docker pull confluentinc/cp-kafka
          docker pull quay.io/strimzi/kafka:0.36.0-kafka-3.5.0
          eval $(minikube docker-env -u)
          ./mvnw install -pl e2e-tests -am -DskipTests
          ./mvnw verify -pl e2e-tests          
