#
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

topics:
  - name: "questions-topic"
    creation-mode: create-if-not-exists
  - name: "answers-topic"
    creation-mode: create-if-not-exists
errors:
    on-failure: "skip"
pipeline:
  - name: "convert-to-structure"
    type: "document-to-json"
    input: "questions-topic"
    configuration:
      text-field: "question"
  - name: "compute-embeddings"
    type: "compute-ai-embeddings"
    configuration:
      model: "amazon.titan-embed-text-v1"
      embeddings-field: "value.embeddings_vector"
      text: "{{ value.question }}"
      batch-size: 10
      flush-interval: 500
  - name: "lookup-related-documents"
    type: "query-vector-db"
    configuration:
      datasource: "OpenSearch"
      query: |
        {
          "index": "rag-index-example-3",
          "size": 10,
          "query": {
            "knn": {
              "embeddings": {
                "vector": ?,
                "k": 10
              }
            }
          }
        }
      fields:
        - "value.embeddings_vector"
      output-field: "value.related_documents"
  - name: "re-rank documents with MMR"
    type: "re-rank"
    configuration:
      max: 5 # keep only the top 5 documents, because we have an hard limit on the prompt size
      field: "value.related_documents"
      query-text: "value.question"
      query-embeddings: "value.embeddings_vector"
      output-field: "value.related_documents"
      text-field: "record.document.content"
      embeddings-field: "record.document.embeddings"
      algorithm: "MMR"
      lambda: 0.5
      k1: 1.2
      b: 0.75
  - name: "ai-chat-completions"
    type: "ai-chat-completions"
    configuration:
      model: "anthropic.claude-v2"
      completion-field: "value.answer"
      min-chunks-per-message: 5
      log-field: "value.prompt"
      options:
        request-parameters:
          temperature: 0.8
          max_tokens_to_sample: 200
          top_p: 0.9
          top_k: 250
        response-completions-expression: "completion"
      messages:
        - content: |
            
            Human: 
            
            
            The user is asking questions about books. Please provide an answer to him as response and add an explanation. Do not respond with generic information, only use the information provided in this prompt. If you don't know, just say so.
            The user question is: "{{ value.question}}?".
            Information you can use are the following:
            
            {{# value.related_documents}}
            #####
            {{ document.content }}
            {{/ value.related_documents}}
            
            Assistant:
  - name: "Format response"
    type: compute
    output: "answers-topic"
    configuration:
      fields:
        - name: "value"
          type: STRING
          expression: "value.answer"
