#
#
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

configuration:
  resources:
  - type: "bedrock-configuration"
    name: "Bedrock"
    configuration:
      access-key: "${secrets.bedrock.access-key}"
      secret-key: "${secrets.bedrock.secret-key}"
      region: "${secrets.bedrock.region}"
  - type: "vector-database"
    name: "OpenSearch"
    configuration:
      service: "opensearch"
      username: "${secrets.opensearch.username}"
      password: "${secrets.opensearch.password}"
      host: "${secrets.opensearch.host}"
      port: "${secrets.opensearch.port}"
      https: "${secrets.opensearch.https}"
      region: "${secrets.opensearch.region}"